name: Java CI
on: push
jobs:
  Clone-down:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: checkout
      uses: actions/checkout@v2
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    needs: Clone-down
    steps:
      - name: my-step
      run: ci/build-app.sh
      - name: Upload Repo
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .
  Test:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    needs: Clone-down
    steps:
      - name: my-test
      run: ci/unit-test-app.sh

 # my-job:
 #   runs-on: ubuntu-latest
 #   container: gradle:6-jdk11
 #   steps:
 #     - uses: actions/checkout@v2
 #     - name: my-step
 #       run: ci/build-app.sh
 #     - name: my-test
 #       run: ci/unit-test-app.sh
 #     - name: Upload Repo
 #       uses: actions/upload-artifact@v2
 #       with:
 #         name: code
 #         path: .